// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using APIClient.Infrastructure.Data.Entities;

#nullable disable

namespace APIClient.Infrastructure.Data.Contexts
{
    public partial class AsignacionContext : DbContext
    {
        public AsignacionContext()
        {
        }

        public AsignacionContext(DbContextOptions<AsignacionContext> options)
            : base(options)
        {
          //  Database.Migrate();
        }

        public virtual DbSet<Aplicativo> Aplicativo { get; set; }
        public virtual DbSet<Carga> Carga { get; set; }
        public virtual DbSet<Periodo> Periodo { get; set; }
        public virtual DbSet<PorcentajeAsignacion> PorcentajeAsignacion { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Squad> Squad { get; set; }
        public virtual DbSet<Tribucoe> Tribucoe { get; set; }

        public virtual DbSet<Asignacion> Asignacion { get; set; }

        //public virtual DbSet<Asignacion> AsignacionActivos { get; set; }
        public virtual DbSet<CargaSiga> CargaSiga { get; set; }
        public virtual DbSet<CargaSigaH> CargaSigaH { get; set; }
        public virtual DbSet<Login> Login { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.AplicativoConfiguration());
            //modelBuilder.Entity<Aplicativo>();
            ////.HasNoKey()
            ////.ToView("AplicativoView");
            
            modelBuilder.ApplyConfiguration(new Configurations.LoginConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AsignacionConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RolConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SquadConfiguration());
            

            modelBuilder.ApplyConfiguration(new Configurations.TribuCoeConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PorcentajeAsignacionConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PeriodoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CargaConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CargaSigaConfiguration());
            //modelBuilder.Entity<CargaSiga>()
            //.HasNoKey()
            //.ToView("CargaView");

            OnModelCreatingPartial(modelBuilder);

          //  OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}