// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace APIClient.Infrastructure.Data.Entities
{

    public partial class Asignacion
    {
        // internal object idRol;

         

        //   public static object Rol { get; internal set; }
        [Key]
        public int IdPorcentajeAsignacion { get; set; }
        public string MatriculaUsuario { get; set; }
        public string ApellidopaternoUsuario { get; set; }
        public string ApellidomaternoUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string NombreChapter { get; set; }
        public string MatriculaChapter { get; set; }
        public int? IdRol { get; set; }
        public string Especialidad { get; set; }
        public int? IdSquad { get; set; }
        public int? IdAplicativo { get; set; }
        public double? Porcentaje { get; set; }
        public string Comentarios { get; set; }
        public string FechaPeriodoAprobado { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string UsuarioRegistro { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public bool? Estado { get; set; }
        public bool? EstadoRegistro { get; set; }

        //[JsonIgnore]
        public virtual Rol Rol { get; set; }
        //  [JsonIgnore]
        public virtual Aplicativo Aplicativo { get; set; }
        // [JsonIgnore]
        public virtual Squad Squad { get; set; }

        //public virtual Rol Rol { get; set; }


    }
}