// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace APIClient.Infrastructure.Data.Entities
{
    public partial class Carga
    {
        [Key]
        public int IdCarga { get; set; }
        public int? IdPeriodo { get; set; }
        public string NombreCal { get; set; }
        public string MatriculaCal { get; set; }
        public string NombreChapter { get; set; }
        public string MatriculaChapter { get; set; }
        public string TipoPreper { get; set; }
        public string Empresa { get; set; }
        public string MatriculaUsuario { get; set; }
        public string ApellidopaternoUsuario { get; set; }
        public string ApellidomaternoUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string ChapterUo { get; set; }
       public DateTime? FechaCarga { get; set; }

        public Periodo Period { get; set; } //Objeto de navegación virtual EFC

    }
}