// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace APIClient.Infrastructure.Data.Entities
{
    public partial class Rol
    {

        //public Rol()
        //{
        //    Asignars = new HashSet<Asignacion>();
        //}
         [Key]
        public int IdRol { get; set; }
        public string SqRol { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string UsuarioRegistro { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public bool? Estado { get; set; }

        [JsonIgnore]
        public ICollection<Asignacion> Asignacion { get; set; }

        // public Asignacion Asignacion { get; set; }
        //  public virtual ICollection<Asignacion> Asignars { get; set; }
        //  public IEnumerable <Asignacion> Asignars { get; set; }
        //public virtual Asignacion Asignacion { get; set; }

        //  public virtual ICollection<Book> Books { get; set; }
    }
}