// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace APIClient.Infrastructure.Data.Entities
{
    public partial class Squad
    {


        
        [Key]
        public int IdSquad { get; set; }
        public string CodSquad { get; set; }
        public string NombreSquad { get; set; }
        public int? IdTribucoe { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string UsuarioRegistro { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public bool? Estado { get; set; }

        // [JsonIgnore] HERE or
       //  [JsonIgnore]
        public virtual Tribucoe Tribucoe { get; set; }

       [JsonIgnore]
        public ICollection<Asignacion> Asignacion { get; set; }

    }
}