// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace APIClient.Infrastructure.Data.Entities
{
    public partial class Tribucoe
    {

        [Key]
        public int IdTribucoe { get; set; }
        public string CodTribucoe { get; set; }
        public string NombreTribucoe { get; set; }
        public string CategoriaTribucoe { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public string UsuarioRegistro { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public bool? Estado { get; set; }

        // [JsonIgnore] or HERE
        [JsonIgnore]
        public ICollection<Squad> Squad { get; set; }
    }
}